Repository august-thirty-first/frontend, pull requests merged in 2023-08, with the labels that each got.

#19 [feat] : home 레이아웃 생성
  next/src/app/(home)/channel/layout.tsx
  next/src/app/(home)/channel/page.tsx
  next/src/app/(home)/ladder/layout.tsx
  next/src/app/(home)/ladder/page.tsx
  next/src/app/(home)/layout.tsx
  next/src/app/(home)/profile/layout.tsx
  next/src/app/(home)/profile/page.tsx
  next/src/app/favicon.ico
  next/src/app/globals.css
  next/src/app/layout.tsx
  next/src/app/page.tsx
  next/src/components/alarms.tsx
  next/src/components/friends.tsx
  next/src/components/navigation.tsx
  next/src/interfaces/childrenProps.interface.ts
Labels: 💫feat

#22 auth 기능 구현 완료
  next/public/next.svg
  next/public/vercel.svg
  next/src/app/(login)/layout.tsx
  next/src/app/(login)/login/page.tsx
  next/src/app/(login)/signup/page.tsx
  next/src/app/favicon.ico
  next/src/app/layout.tsx
  next/src/app/page.tsx
  next/src/components/btn.tsx
  next/src/components/redirectBtn.tsx
  next/src/components/welcome.tsx
  next/src/style/globals.css
  next/tailwind.config.js
Labels: 💫feat

#23 Home 레이아웃 구성 완료
  next/src/app/(home)/channel/layout.tsx
  next/src/app/(home)/channel/page.tsx
  next/src/app/(home)/ladder/layout.tsx
  next/src/app/(home)/ladder/page.tsx
  next/src/app/(home)/layout.tsx
  next/src/app/(home)/profile/layout.tsx
  next/src/app/(home)/profile/page.tsx
  next/src/app/layout.tsx
  next/src/components/alarms.tsx
  next/src/components/friends.tsx
  next/src/components/navigation.tsx
  next/src/interfaces/childrenProps.interface.ts
Labels: 💫feat

#31 Feat 로그인 후 클라이언트 소켓 세팅
  next/package-lock.json
  next/package.json
  next/src/app/(home)/(communication)/channel/layout.tsx
  next/src/app/(home)/(communication)/channel/page.tsx
  next/src/app/(home)/(communication)/ladder/layout.tsx
  next/src/app/(home)/(communication)/ladder/page.tsx
  next/src/app/(home)/(communication)/layout.tsx
  next/src/app/(home)/(communication)/profile/layout.tsx
  next/src/app/(home)/(communication)/profile/page.tsx
  next/src/app/(home)/(game)/createGameSocketContext.tsx
  next/src/app/(home)/(game)/game/page.tsx
  next/src/app/(home)/(game)/layout.tsx
  next/src/app/(home)/createHomeSocketContext.tsx
  next/src/app/(home)/layout.tsx
  next/src/app/layout.tsx
  next/src/components/navigation.tsx
Labels: 💫feat

#30 [feat] 로그인 여부에 따른 redirect 처리 추가
  next/src/app/(home)/layout.tsx
  next/src/app/page.tsx
Labels: 💫feat

#35 Feat 소켓 사용시 컴파일 warning 발생 해결
  next/package-lock.json
  next/package.json
Labels: 🐛bug

#41 게임 옵션 창 레이아웃 구현
  Dockerfile
  docker-compose.yml
  next/src/app/(home)/(game)/createGameSocketContext.tsx
  next/src/app/(home)/(game)/game/option/page.tsx
  next/src/app/(home)/createHomeSocketContext.tsx
  next/src/components/(home)/(game)/game/checkBox.tsx
  next/src/components/(home)/(game)/game/difficultySelection.tsx
  next/src/components/(home)/(game)/game/gameOptionSubmitForm.tsx
  next/src/components/(home)/(game)/game/typeSelection.tsx
  next/src/components/btn.tsx
  run.sh
Labels: 💫feat

#42 checkbox 컴포넌트 생성 및 form 데이터를 체크할 수 있는 submitform 컴포넌트 생성
  next/src/app/(home)/(game)/createGameSocketContext.tsx
  next/src/app/(home)/(game)/game/option/page.tsx
  next/src/components/(home)/(game)/game/checkBox.tsx
  next/src/components/(home)/(game)/game/difficultySelection.tsx
  next/src/components/(home)/(game)/game/gameOptionSubmitForm.tsx
  next/src/components/(home)/(game)/game/typeSelection.tsx
  next/src/components/btn.tsx
Labels: 💫feat, 🙋question

#54 dev-game 브랜치에 release-1.0 병합
  docker-compose.yml
  next/next.config.js
  next/src/app/(home)/(communication)/channel/chat/page.tsx
  next/src/app/(home)/(communication)/channel/enterRoom.tsx
  next/src/app/(home)/(communication)/channel/layout.tsx
  next/src/app/(home)/(communication)/channel/page.tsx
  next/src/app/(home)/(communication)/profile/edit/nickname.tsx
  next/src/app/(home)/(communication)/profile/edit/otp.tsx
  next/src/app/(home)/(communication)/profile/edit/otpModal.tsx
  next/src/app/(home)/(communication)/profile/edit/page.tsx
  next/src/app/(home)/(communication)/profile/info.tsx
  next/src/app/(home)/(communication)/profile/page.tsx
  next/src/app/(home)/(communication)/profile/searchBar.tsx
  next/src/app/(home)/createHomeSocketContext.tsx
  next/src/app/(login)/otp/page.tsx
  next/src/app/(login)/signup/avata.tsx
  next/src/app/(login)/signup/nickname.tsx
  next/src/app/(login)/signup/page.tsx
  next/src/app/layout.tsx
  next/src/components/(login)/signup/nickname.tsx
  next/src/components/btn.tsx
  next/src/components/logout.tsx
  next/src/components/modal/Modal.tsx
  next/src/components/modal/ModalContent.tsx
  next/src/components/modal/ModalHeader.tsx
  next/src/components/submitForm.tsx
  next/src/lib/interface/commonError.interface.ts
  next/src/lib/interface/commonResponse.interface.ts
  next/src/lib/useFetch.ts
  next/src/public/default.png
  next/src/style/globals.css
Labels: ⚙️chore

#62 게임 옵션 창 레이아웃 구현
  next/src/app/layout.tsx
  next/src/components/(home)/(game)/game/difficultySelection.tsx
  next/src/components/(home)/(game)/game/gameOptionSubmitForm.tsx
  next/src/components/(home)/(game)/game/typeSelection.tsx
Labels: 💫feat

#60 Feat 50 친구 기능 만들기
  next/package-lock.json
  next/package.json
  next/src/app/(home)/(communication)/profile/_friend/friendActionBtn.tsx
  next/src/app/(home)/(communication)/profile/_friend/friendBtn.tsx
  next/src/app/(home)/(communication)/profile/page.tsx
  next/src/app/(home)/(communication)/profile/searchBar.tsx
  next/src/components/friends.tsx
  next/src/lib/useFetch.ts
Labels: 💫feat

#69 61 알림 목록에 알림 데이터 추가하기
  next/src/app/(home)/(communication)/profile/_friend/friendBtn.tsx
  next/src/app/(home)/(communication)/profile/page.tsx
  next/src/components/alarms.tsx
  next/src/components/friends.tsx
Labels: 💫feat

#68 [bug] 로그아웃시에 Home Socket 연결 해제
  next/src/components/logout.tsx
Labels: 🐛bug

#76 방 입장 관련 로직 구현
  next/src/app/(home)/(communication)/channel/_list/chatRoomList.tsx
  next/src/app/(home)/(communication)/channel/_room/allRoomList.tsx
  next/src/app/(home)/(communication)/channel/_room/myRoomList.tsx
  next/src/app/(home)/(communication)/channel/_room/roomBuilder.tsx
  next/src/app/(home)/(communication)/channel/_room/roomDetails.tsx
  next/src/app/(home)/(communication)/channel/_room/roomList.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/chatBox.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/delete.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/page.tsx
  next/src/app/(home)/(communication)/channel/chat/page.tsx
  next/src/app/(home)/(communication)/channel/layout.tsx
  next/src/interfaces/chatParticipant.interface.ts
  next/src/interfaces/chatRoom.interface.ts
  next/src/style/globals.css
Labels: 💫feat

#80 [bug] 소켓 disconnect logout 처리
  next/src/components/logout.tsx
Labels: 🐛bug

#92 [bug] server component socket 연결 해제
  next/src/app/(home)/(game)/createGameSocketContext.tsx
  next/src/app/(home)/createHomeSocketContext.tsx
Labels: 🐛bug

#89 Bug 88 소켓 연결 끊기 예외 처리
  next/src/components/logout.tsx
  next/src/lib/useFetch.ts
Labels: 🐛bug

#90 소켓 채팅이 되지 않는 문제 해결
  next/src/app/(home)/(communication)/channel/_room/roomDetails.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/chatBox.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/page.tsx
Labels: 🐛bug

#107 게임 스크린 모양 완성하기
  next/src/app/(home)/(communication)/channel/_room/roomBuilder.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/delete.tsx
  next/src/app/(home)/(communication)/profile/_friend/friendActionBtn.tsx
  next/src/app/(home)/(communication)/profile/edit/nickname.tsx
  next/src/app/(home)/(communication)/profile/edit/otpModal.tsx
  next/src/app/(home)/(communication)/profile/edit/page.tsx
  next/src/app/(home)/(communication)/profile/searchBar.tsx
  next/src/app/(home)/(game)/game/gameScreen.tsx
  next/src/app/(home)/(game)/game/page.tsx
  next/src/app/(home)/(game)/game/renderInfo.tsx
  next/src/app/(login)/otp/page.tsx
  next/src/app/(login)/signup/avata.tsx
  next/src/app/(login)/signup/nickname.tsx
  next/src/app/(login)/signup/page.tsx
  next/src/app/ShowModalContext.tsx
  next/src/app/layout.tsx
  next/src/components/logout.tsx
  next/src/lib/useFetch.ts
Labels: 💫feat

#108 Feat chat 채팅방 나가기
  next/src/app/(home)/(communication)/channel/MyParticipantInfoContext.tsx
  next/src/app/(home)/(communication)/channel/_room/roomDetails.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/leave.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/page.tsx
  next/src/app/(home)/(communication)/channel/layout.tsx
  next/src/app/(home)/(communication)/channel/page.tsx
Labels: 🐛bug, 💫feat

#116 114 user profile achivement 출력 및 layout 재구성
  next/src/app/(home)/(communication)/profile/achievements.tsx
  next/src/app/(home)/(communication)/profile/info.tsx
  next/src/app/(home)/(communication)/profile/matchHistory.tsx
  next/src/app/(home)/(communication)/profile/page.tsx
  next/src/app/(home)/(communication)/profile/searchBar.tsx
Labels: 💫feat

#117 Feat toast bar 구현
  next/src/app/layout.tsx
  next/src/components/Toast.css
  next/src/components/toast.tsx
  next/src/components/toastContext.tsx
Labels: 💫feat

#125 [Fix]: api 주소 변경
  next/src/app/(home)/(communication)/channel/_room/allRoomList.tsx
  next/src/app/(home)/(communication)/channel/_room/myRoomList.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/_participant/authority.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/delete.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/page.tsx
Labels: 🐛bug, ⚙️chore

#128 127 프로필 게임 data 출력
  next/src/app/(home)/(communication)/profile/matchHistory.tsx
  next/src/app/(home)/(communication)/profile/page.tsx
  next/src/app/(home)/(communication)/profile/searchBar.tsx
Labels: 💫feat

#132 [bug] 프로필 변경시 socket reconnect
  next/src/app/(home)/(communication)/profile/edit/page.tsx
Labels: 🐛bug

#130 Hotfix 채팅방 생성 삭제 등 작업시 목록이 갱신되지 않음
  next/src/app/(home)/(communication)/channel/_room/allRoomList.tsx
  next/src/app/(home)/(communication)/channel/_room/myRoomList.tsx
  next/src/app/(home)/(communication)/channel/_room/roomBuilder.tsx
  next/src/app/(home)/(communication)/channel/_room/roomDetails.tsx
  next/src/app/(home)/(communication)/channel/_room/roomList.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/_participant/SetMyParticipantInfo.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/_participant/authority.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/_participant/ban.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/_participant/kick.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/_participant/mute.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/leave.tsx
  next/src/app/(home)/(communication)/channel/chat/[id]/page.tsx
Labels: 🐛bug, 💫feat

#147 [feat] 레더 점수 출력시키기
  next/src/app/(home)/(communication)/profile/matchHistory.tsx
  next/src/app/(home)/(communication)/profile/searchBar.tsx
Labels: 💫feat

#146 [bug] achievement List 콘솔 에러
  next/src/app/(home)/(communication)/profile/achievements.tsx
Labels: 🐛bug

#145 [bug] match list의 key Props 설정
  next/src/app/(home)/(communication)/profile/matchHistory.tsx
Labels: 🐛bug

#164 1:1게임 요청과 수락, 매칭 후 대기페이지(/general) 구현
  next/src/app/(home)/(game)/game/general/page.tsx
  next/src/app/(home)/createHomeSocketContext.tsx
  next/src/components/friends.tsx
  next/src/components/playGameBtn.tsx
  next/src/components/toast.tsx
  next/src/components/toastContext.tsx
Labels: 💫feat

#182 [Remove]: 비밀번호 칸 disable되는 현상 삭제
  next/src/app/(home)/(communication)/channel/_room/roomBuilder.tsx
Labels: 🐛bug
